### ISSUE TITLE
How to initialize db?

### ISSUE THREAD

**Issue by ynych** [snibox/snibox#34]
```
I, [2018-10-13T21:57:22.341415 #53626]  INFO -- : [5cdb2a96-a7c3-4a79-9188-476d39a54de3] Started GET "/login" for 127.0.0.1 at 2018-10-13 21:57:22 +0800
I, [2018-10-13T21:57:22.342866 #53626]  INFO -- : [5cdb2a96-a7c3-4a79-9188-476d39a54de3] Processing by SessionsController#new as HTML
I, [2018-10-13T21:57:22.374921 #53626]  INFO -- : [5cdb2a96-a7c3-4a79-9188-476d39a54de3] Completed 500 Internal Server Error in 32ms (ActiveRecord: 12.6ms)
F, [2018-10-13T21:57:22.376764 #53626] FATAL -- : [5cdb2a96-a7c3-4a79-9188-476d39a54de3]
F, [2018-10-13T21:57:22.376848 #53626] FATAL -- : [5cdb2a96-a7c3-4a79-9188-476d39a54de3] ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "users" does not exist
LINE 8:                WHERE a.attrelid = '"users"'::regclass
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
                     c.collname, col_description(a.attrelid, a.attnum) AS comment
                FROM pg_attribute a
                LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
                LEFT JOIN pg_type t ON a.atttypid = t.oid
                LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
               WHERE a.attrelid = '"users"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum
):
F, [2018-10-13T21:57:22.376931 #53626] FATAL -- : [5cdb2a96-a7c3-4a79-9188-476d39a54de3]
F, [2018-10-13T21:57:22.377005 #53626] FATAL -- : [5cdb2a96-a7c3-4a79-9188-476d39a54de3] activerecord (5.2.1) lib/active_record/connection_adapters/postgresql/database_statements.rb:63:in `async_exec'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] activerecord (5.2.1) lib/active_record/connection_adapters/postgresql/database_statements.rb:63:in `block (2 levels) in query'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] activesupport (5.2.1) lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] activesupport (5.2.1) lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] activesupport (5.2.1) lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] activerecord (5.2.1) lib/active_record/connection_adapters/postgresql/database_statements.rb:62:in `block in query'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] activerecord (5.2.1) lib/active_record/connection_adapters/abstract_adapter.rb:579:in `block (2 levels) in log'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] /Users/yyc/.rbenv/versions/2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] activerecord (5.2.1) lib/active_record/connection_adapters/abstract_adapter.rb:578:in `block in log'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] activesupport (5.2.1) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] activerecord (5.2.1) lib/active_record/connection_adapters/abstract_adapter.rb:569:in `log'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] activerecord (5.2.1) lib/active_record/connection_adapters/postgresql/database_statements.rb:61:in `query'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] activerecord (5.2.1) lib/active_record/connection_adapters/postgresql_adapter.rb:749:in `column_definitions'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] activerecord (5.2.1) lib/active_record/connection_adapters/abstract/schema_statements.rb:113:in `columns'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] activerecord (5.2.1) lib/active_record/connection_adapters/schema_cache.rb:69:in `columns'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] activerecord (5.2.1) lib/active_record/connection_adapters/schema_cache.rb:75:in `columns_hash'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] activerecord (5.2.1) lib/active_record/model_schema.rb:466:in `load_schema!'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] activerecord (5.2.1) lib/active_record/attributes.rb:234:in `load_schema!'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] activerecord (5.2.1) lib/active_record/attribute_decorators.rb:51:in `load_schema!'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] activerecord (5.2.1) lib/active_record/model_schema.rb:459:in `block in load_schema'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] /Users/yyc/.rbenv/versions/2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] activerecord (5.2.1) lib/active_record/model_schema.rb:456:in `load_schema'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] activerecord (5.2.1) lib/active_record/model_schema.rb:346:in `attribute_types'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] activerecord (5.2.1) lib/active_record/attribute_methods.rb:230:in `has_attribute?'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] activerecord (5.2.1) lib/active_record/inheritance.rb:55:in `new'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] devise (4.4.3) app/controllers/devise/sessions_controller.rb:11:in `new'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] actionpack (5.2.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] actionpack (5.2.1) lib/abstract_controller/base.rb:194:in `process_action'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] actionpack (5.2.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] actionpack (5.2.1) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] activesupport (5.2.1) lib/active_support/callbacks.rb:132:in `run_callbacks'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] actionpack (5.2.1) lib/abstract_controller/callbacks.rb:41:in `process_action'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] actionpack (5.2.1) lib/action_controller/metal/rescue.rb:22:in `process_action'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] actionpack (5.2.1) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] activesupport (5.2.1) lib/active_support/notifications.rb:168:in `block in instrument'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] activesupport (5.2.1) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] activesupport (5.2.1) lib/active_support/notifications.rb:168:in `instrument'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] actionpack (5.2.1) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] actionpack (5.2.1) lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] activerecord (5.2.1) lib/active_record/railties/controller_runtime.rb:24:in `process_action'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] actionpack (5.2.1) lib/abstract_controller/base.rb:134:in `process'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] actionview (5.2.1) lib/action_view/rendering.rb:32:in `process'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] actionpack (5.2.1) lib/action_controller/metal.rb:191:in `dispatch'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] actionpack (5.2.1) lib/action_controller/metal.rb:252:in `dispatch'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] actionpack (5.2.1) lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] actionpack (5.2.1) lib/action_dispatch/routing/route_set.rb:34:in `serve'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] actionpack (5.2.1) lib/action_dispatch/routing/mapper.rb:18:in `block in <class:Constraints>'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] actionpack (5.2.1) lib/action_dispatch/routing/mapper.rb:48:in `serve'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] actionpack (5.2.1) lib/action_dispatch/journey/router.rb:52:in `block in serve'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] actionpack (5.2.1) lib/action_dispatch/journey/router.rb:35:in `each'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] actionpack (5.2.1) lib/action_dispatch/journey/router.rb:35:in `serve'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] actionpack (5.2.1) lib/action_dispatch/routing/route_set.rb:840:in `call'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] warden (1.2.7) lib/warden/manager.rb:35:in `catch'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] warden (1.2.7) lib/warden/manager.rb:35:in `call'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] rack (2.0.5) lib/rack/tempfile_reaper.rb:15:in `call'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] rack (2.0.5) lib/rack/etag.rb:25:in `call'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] rack (2.0.5) lib/rack/conditional_get.rb:25:in `call'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] rack (2.0.5) lib/rack/head.rb:12:in `call'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] actionpack (5.2.1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] rack (2.0.5) lib/rack/session/abstract/id.rb:232:in `context'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] rack (2.0.5) lib/rack/session/abstract/id.rb:226:in `call'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] actionpack (5.2.1) lib/action_dispatch/middleware/cookies.rb:670:in `call'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] actionpack (5.2.1) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] activesupport (5.2.1) lib/active_support/callbacks.rb:98:in `run_callbacks'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] actionpack (5.2.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] actionpack (5.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] actionpack (5.2.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] railties (5.2.1) lib/rails/rack/logger.rb:38:in `call_app'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] railties (5.2.1) lib/rails/rack/logger.rb:26:in `block in call'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] activesupport (5.2.1) lib/active_support/tagged_logging.rb:71:in `block in tagged'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] activesupport (5.2.1) lib/active_support/tagged_logging.rb:28:in `tagged'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] activesupport (5.2.1) lib/active_support/tagged_logging.rb:71:in `tagged'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] railties (5.2.1) lib/rails/rack/logger.rb:26:in `call'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] actionpack (5.2.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] actionpack (5.2.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] rack (2.0.5) lib/rack/method_override.rb:22:in `call'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] rack (2.0.5) lib/rack/runtime.rb:22:in `call'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] activesupport (5.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] actionpack (5.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] actionpack (5.2.1) lib/action_dispatch/middleware/static.rb:127:in `call'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] rack (2.0.5) lib/rack/sendfile.rb:111:in `call'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] railties (5.2.1) lib/rails/engine.rb:524:in `call'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] puma (3.12.0) lib/puma/configuration.rb:225:in `call'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] puma (3.12.0) lib/puma/server.rb:658:in `handle_request'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] puma (3.12.0) lib/puma/server.rb:472:in `process_client'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] puma (3.12.0) lib/puma/server.rb:332:in `block in run'
[5cdb2a96-a7c3-4a79-9188-476d39a54de3] puma (3.12.0) lib/puma/thread_pool.rb:133:in `block in spawn_thread'
```

**Comment by Snowmean** [comment]
Have you try to run

```
rails db:migrate
```

**Comment by vavgustov** [comment]
no response - closed as deprecated
